server:
  port: 9877


spring:
  sleuth:
    enabled: true # 开启Sleuth
    sampler:
      probability: 1 # 采样率，默认是0.1
      refresh:
        enabled: true # 是否刷新
      rate: 10 # 每秒采样频率
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web # zipkin采样存储类型，web默认就是HTTP，其他的MQ异步的方式


eureka:
  server:
    enable-self-preservation: false # 是否开启自我保护
  instance:
    appname: ${spring.application.name} # 应用服务名称
    hostname: eureka-server-B
    prefer-ip-address: true # 偏向IP
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}:@project.version@
    ip-address: 192.168.202.9 # 指定IP地址
    lease-renewal-interval-in-seconds: 30 # 续租时间间隔
    lease-expiration-duration-in-seconds: 90 # 过期时间
  client:
    service-url:
      defaultZone: http://eureka-server-A:9876/eureka,http://eureka-server-B:9877/eureka # 注册中心服务列表
    fetch-registry: true # 拉取服务列表
    register-with-eureka: true # 是否注册到注册中心
    healthcheck:
      enabled: true # 默认开启监控检查

# 日志配置
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug

# 监控
management:
  endpoints:
    web:
      exposure:
        include: "*"


