server:
  port: 9877

eureka:
  server:
    enable-self-preservation: false # 是否开启自我保护
  instance:
    appname: ${spring.application.name} # 应用服务名称
    hostname: eureka-server-B
    prefer-ip-address: true # 偏向IP
    lease-renewal-interval-in-seconds: 30 # 续租时间间隔
    lease-expiration-duration-in-seconds: 90 # 过期时间
  client:
    service-url:
      defaultZone: http://eureka-server-A:9876/eureka,http://eureka-server-B:9877/eureka # 注册中心服务列表
    fetch-registry: true # 拉取服务列表
    register-with-eureka: true # 是否注册到注册中心
