version: "3.9"
services:
  pandas-auth:
    container_name: pandas-auth-1.0
    image: pandas-auth:1.0
    build:
      dockerfile: Dockerfile
      context: pandas-auth
  pandas-eureka:
    container_name: pandas-eureka-1.0
    image: pandas-eureka:1.0
    build:
      context: pandas-eureka
      dockerfile: Dockerfile
  nacos-server:
    image: nacos/nacos-server:v2.2.0
    hostname: nacos-server
    container_name: nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"

