server:
  port: 8095

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true # 默认开启负载均衡
  sleuth:
    enabled: true # 开启Sleuth
    sampler:
      probability: 1 # 采样率，默认是0.1
      refresh:
        enabled: true # 是否刷新
      rate: 10 # 每秒采样频率
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web # zipkin采样存储类型，web默认就是HTTP，其他的MQ异步的方式

eureka:
  instance:
    appname: ${spring.application.name} # 应用服务名称
    prefer-ip-address: true # 偏向IP
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}:@project.version@
    ip-address: 192.168.202.9 # 指定IP地址
    lease-renewal-interval-in-seconds: 30 # 续租时间间隔
    lease-expiration-duration-in-seconds: 90 # 过期时间
  client:
    service-url:
      defaultZone: http://eureka-server-A:9876/eureka,http://eureka-server-B:9877/eureka # 注册中心服务列表
    fetch-registry: true # 拉取服务列表
    register-with-eureka: true # 是否注册到注册中心


# 负载均衡，指定服务的话则为全局
ORDER-SERVICE:
  ribbon:
    ConnectTimeOut: 1000 # 连接超市时间
    ReadTimeOut: 10000 # 请求处理时间
    OkToRetyrOnAllOperations: true # 对所有操作都重试
    MaxAutoRetyiesNextServer: 2 # 切换实例重拾次数
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule # 负载均衡策略

